package altrisi.scarpetapptester.tests;

import java.util.ArrayList;
import java.util.List;

import altrisi.scarpetapptester.AppTesterThread;
import carpet.script.Context;
import carpet.script.LazyValue;
import carpet.script.value.FunctionValue;
import carpet.script.value.StringValue;

public class ScarpetGeneratedTest implements Test {
	private App app = AppTesterThread.INSTANCE.getCurrentApp();
	private String testName;
	private FunctionValue prepare, pre, post, check;
	private TestSubject testSubject;
	private boolean finished;
	private Context context;
	private TestStage stage;
	
	public ScarpetGeneratedTest(String name, TestSubject test, FunctionValue prepare, FunctionValue pre, FunctionValue post, FunctionValue check, Context ctx) {
		this.testName = name;
		this.prepare = prepare;
		this.pre = pre;
		this.post = post;
		this.testSubject = test;
		this.check = check;
		this.context = ctx;
	}
	
	@Override
	public App getApp() {
		return app;
	}

	@Override
	public String getTestName() {
		return testName;
	}

	@Override
	public void runTests() {
		// TODO Autogenerated method stub (okno)
		testSubject.call();
	}
	
	@Override
	public void preTesting() {
		callWithArgs(prepare);
	}
	
	@Override
	public void rightBeforeTestingStarts() {
		callWithArgs(pre);
	}
	
	@Override
	public void rightAfterTestingStarts() {
		callWithArgs(post);
	}
	
	@Override
	public void afterTesting() {
		callWithArgs(check);
	}

	private void callWithArgs(FunctionValue function) {
		if (function == null) return;
		List<LazyValue> params = new ArrayList<LazyValue>();
		params.add((c, t) -> new StringValue(getTestName()));
		params.add((c, t) -> new StringValue(getTestStage().toString().toLowerCase()));
		function.callInContext(context, 0, params);
	}
	
	@Override
	public TestResults getResults() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public boolean isFinished() {
		return finished;
	}
	
	@Override
	public void setFinished() {
		finished = true;
	}
	@Override
	public TestStage getTestStage() {
		return stage;
	}
	
	@Override
	public void setStage(TestStage stage) {
		this.stage = stage;
	}

	// We can't use those, since we need to run on main thread
	@Override public boolean successfulSoFar() { return true; }
	@Override public void testFinishedChecks() { }
	@Override public void finishTest() { }
	@Override public void prepareTest() { }

}
