Bug Squashing:
  Needs triage:
    - 'triage'
  Low priority:
    - 'low priority'
  High priority:
    - 'high priority'
  In Progress:
    - 'in progress'
Progress tracking:
  To do:
    - 'to do'
  In progress:
    - 'in progress'
